apiVersion: apps/v1
kind: DaemonSet
metadata:
  name: rpi-control
  #namespace: default
spec:
  #replicas: {{ .Values.replicaCount }}
  selector:
    matchLabels:
      app: rpi-control
  template:
    metadata:
      labels:
        app: rpi-control
    spec:
      affinity:
        nodeAffinity:
          requiredDuringSchedulingIgnoredDuringExecution:
            nodeSelectorTerms:
            - matchExpressions:
              - key: sbc_type
                operator: In
                values:
                - rpi3
                - bpizero
      containers:
      - name: rpi-control-container
        image: erostamas/rpi_control_main:latest
        command: ["/usr/bin/rpi_control.py"]
        securityContext:
          privileged: true
        volumeMounts:
        - name: rpi-control-config-path
          mountPath: "/my_files/"
          readOnly: True
        ports:
        - protocol: TCP
          containerPort: 5000
      volumes:
      - name: rpi-control-config-path
        configMap:
          name: rpi-control-config
