apiVersion: v1
kind: Service
metadata:
    name: rpi-control-service
spec:
    type: NodePort
    ports:
    - name: http
      targetPort: 5000
      nodePort: 30016
      port: 5000
      protocol: TCP
    selector:
      app: rpi-control